main/urls.py
from django.urls import path, re_path
from . import views
from django.views.generic import TemplateView

app_name = "main"
urlpatterns = [
    path('', TemplateView.as_view(template_name="index.html")),
	path('api/', views.UserProfileView.as_view(), name="home"),
    path('api/GitUpdate/', views.GitUpdate, name='GitUpdate'),
	path('api/About/', views.InterestView.as_view(), name="about"),
	path('api/contact/', views.ContactProfileView.as_view(), name="contact"),
	path('api/portfolio/', views.PortfolioView.as_view(), name="portfolios"),
	path('api/portfolio/<slug:slug>/', views.PortfolioView.as_view(), name="portfolio"),
	path('api/Experiences/', views.ExperienceView.as_view(), name="Experiences"),
	path('api/Experiences/<slug:slug>/', views.ExperienceDetailView.as_view(), name="Experiences"),
	path('api/Certificates/', views.CertificateView.as_view(), name="Certificates"),
    # re_path(r'.*', TemplateView.as_view(template_name="index.html")),
	]

portfolio/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
    re_path(r"(?!(api)).*/", TemplateView.as_view(template_name="index.html")),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from ckeditor.fields import RichTextField

class Category(models.Model):
    name = models.CharField(max_length=20)
    order = models.IntegerField(default=1)

    is_active = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

class Skill(models.Model):
    category = models.ForeignKey(Category,
                                on_delete=models.CASCADE)
    name = models.CharField(max_length=20)
    is_active = models.BooleanField(default=True)
    order = models.IntegerField(default=1)

    class Meta:
        verbose_name_plural = 'Skills'
        verbose_name = 'SKill'
        ordering = ["-order"]

    def __str__(self):
        return self.name

class UserProfile(models.Model):

    class Meta:
        verbose_name_plural = 'User Profiles'
        verbose_name = 'User Profile'
    
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(blank=True, null=True, upload_to="avatar")
    title = models.CharField(max_length=200, blank=True, null=True)
    bio = models.TextField(blank=True, null=True)
    bio_personal = models.TextField(blank=True, null=True)
    avatar_personal = models.ImageField(blank=True, null=True, upload_to="avatar")
    skills = models.ManyToManyField(Skill, blank=True)
    categories = models.ManyToManyField(Category, blank=True)
    cv = models.FileField(blank=True, null=True, upload_to="cv")
    linkedin_url = models.CharField(max_length=200, blank=True, null=True)
    github_url = models.CharField(max_length=200, blank=True, null=True)
    gitlab_url = models.CharField(max_length=200, blank=True, null=True)

    def __str__(self):
        return f'{self.user.first_name} {self.user.last_name}'


class Interest(models.Model):

    class Meta:
        verbose_name_plural = 'Interests'
        verbose_name = 'Interest'
    
    title = models.CharField(verbose_name="Title",max_length=100)
    body = RichTextField(blank=True, null=True)
    skills = models.ManyToManyField(Skill, blank=True)
    date = models.CharField(max_length=200, blank=True, null=True)
    url = RichTextField(blank=True, null=True)
    is_active = models.BooleanField(default=True)
    order = models.IntegerField(default=1)
    image = models.ImageField(blank=True, null=True, upload_to="avatar")

    def __str__(self):
        return f'{self.title}'


class ContactProfile(models.Model):
    
    class Meta:
        verbose_name_plural = 'Contact Profiles'
        verbose_name = 'Contact Profile'
        ordering = ["timestamp"]
    timestamp = models.DateTimeField(auto_now_add=True)
    name = models.CharField(verbose_name="Name",max_length=100)
    email = models.EmailField(verbose_name="Email")
    message = models.TextField(verbose_name="Message")

    def __str__(self):
        return f'{self.name}'


class Testimonial(models.Model):

    class Meta:
        verbose_name_plural = 'Testimonials'
        verbose_name = 'Testimonial'
        ordering = ["name"]

    thumbnail = models.ImageField(blank=True, null=True, upload_to="testimonials")
    name = models.CharField(max_length=200, blank=True, null=True)
    role = models.CharField(max_length=200, blank=True, null=True)
    quote = models.CharField(max_length=500, blank=True, null=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name


class Media(models.Model):

    class Meta:
        verbose_name_plural = 'Media Files'
        verbose_name = 'Media'
        ordering = ["name"]
	
    image = models.ImageField(blank=True, null=True, upload_to="media")
    url = models.URLField(blank=True, null=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    is_image = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        if self.url:
            self.is_image = False
        super(Media, self).save(*args, **kwargs)
    def __str__(self):
        return self.name

class Portfolio(models.Model):

    class Meta:
        verbose_name_plural = 'Portfolio Profiles'
        verbose_name = 'Portfolio'
        ordering = ["name"]
    date = models.CharField(max_length=200, blank=True, null=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    description = models.CharField(max_length=500, blank=True, null=True)
    body = RichTextField(blank=True, null=True)
    image = models.ImageField(blank=True, null=True, upload_to="portfolio")
    url = RichTextField(blank=True, null=True)
    slug = models.SlugField(null=True, blank=True)
    is_active = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.name)
        super(Portfolio, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f"/portfolio/{self.slug}"


class Experience(models.Model):

    class Meta:
        verbose_name_plural = 'Experience Profiles'
        verbose_name = 'Experience'
        ordering = ["timestamp"]

    timestamp = models.DateTimeField(auto_now_add=True)
    date = models.CharField(max_length=200, blank=True, null=True)
    location = models.CharField(max_length=200, blank=True, null=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    description = models.CharField(max_length=500, blank=True, null=True)
    body = RichTextField(blank=True, null=True)
    slug = models.SlugField(null=True, blank=True)
    is_active = models.BooleanField(default=True)
    skills = models.ManyToManyField(Skill, blank=True)
    url = RichTextField(blank=True, null=True)
    order = models.IntegerField(default=1)

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.name)
        super(Experience, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f"/Experience/{self.slug}"


class Certificate(models.Model):

    class Meta:
        verbose_name_plural = 'Certificates'
        verbose_name = 'Certificate'

    date = models.CharField(max_length=50, blank=True, null=True)
    organisation = models.CharField(max_length=50, blank=True, null=True)
    title = models.CharField(max_length=200, blank=True, null=True)
    description = RichTextField(blank=True, null=True)
    url = RichTextField(blank=True, null=True)
    skills = models.ManyToManyField(Skill, blank=True)
    is_active = models.BooleanField(default=True)
    order = models.IntegerField(default=1)

    def __str__(self):
        return self.title

main/forms.py
from django import forms
from .models import ContactProfile


class ContactForm(forms.ModelForm):

	name = forms.CharField(max_length=100, required=True,
		widget=forms.TextInput(attrs={
			'placeholder': '*Full name..',
			'class': 'form-control'
			}))
	email = forms.EmailField(max_length=254, required=True, 
		widget=forms.TextInput(attrs={
			'placeholder': '*Email..',
			'class': 'form-control'
			}))
	message = forms.CharField(max_length=1000, required=True, 
		widget=forms.Textarea(attrs={
			'placeholder': '*Message..',
			'class': 'form-control',
			'rows': 6,
			}))


	class Meta:
		model = ContactProfile
		fields = ('name', 'email', 'message',)

main/views.py
from django.shortcuts import render
# from django.contrib import messages
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework import status
from rest_framework.generics import ListAPIView
from rest_framework.generics import RetrieveAPIView
from rest_framework import permissions
from .models import (
		UserProfile,
		Experience,
		Portfolio,
		Certificate,
		ContactProfile,
		Interest
	)
from .serializers import (
		UserProfileSerializer,
		ExperienceSerializer,
		CertificateSerializer,
		PortfolioSerializer,
        ContactProfileSerializer,
		InterestSerializer
	)
from django.views import generic
from . forms import ContactForm
import git,os
from django.views.decorators.csrf import csrf_exempt

class UserProfileView(ListAPIView):
	permission_classes = (permissions.AllowAny, )
	queryset = UserProfile.objects.all()
	serializer_class = UserProfileSerializer
	pagination_class = None
	# template_name = "main/index.html"

	# def get_context_data(self, **kwargs):
	# 	context = super().get_context_data(**kwargs)
		
	# 	testimonials = Testimonial.objects.filter(is_active=True)
	# 	certificates = Certificate.objects.filter(is_active=True).order_by('title').order_by('-order')
	# 	Experiences = Experience.objects.filter(is_active=True).order_by('name').order_by('-order')
	# 	portfolio = Portfolio.objects.filter(is_active=True)
	# 	categories = Category.objects.filter(is_active=True).order_by('name').order_by('-order')
		
	# 	context["testimonials"] = testimonials
	# 	context["certificates"] = certificates
	# 	context["Experiences"] = Experiences
	# 	context["portfolio"] = portfolio
	# 	context["categories"] = categories
	# 	return context


class InterestView(ListAPIView):
	permission_classes = (permissions.AllowAny, )
	queryset = Interest.objects.all().filter(is_active=True).order_by('-order')
	serializer_class = InterestSerializer
	pagination_class = None

class PortfolioView(ListAPIView):
	permission_classes = (permissions.AllowAny, )
	queryset = Portfolio.objects.all()
	serializer_class = PortfolioSerializer
	pagination_class = None
	# model = Portfolio
	# template_name = "main/portfolio.html"
	# paginate_by = 10

	# def get_queryset(self):
	# 	return super().get_queryset().filter(is_active=True)


# class PortfolioDetailView(generic.DetailView):
	# model = Portfolio
	# template_name = "main/portfolio-detail.html"

class ExperienceView(ListAPIView):
	permission_classes = (permissions.AllowAny, )
	queryset = Experience.objects.all().filter(is_active=True).order_by('-order')
	serializer_class = ExperienceSerializer
	pagination_class = None
	# model = Experience
	# template_name = "main/Experience.html"
	# paginate_by = 10
	
	# def get_queryset(self):
	# 	return super().get_queryset().filter(is_active=True).order_by('-order')

class ExperienceDetailView(RetrieveAPIView):
	permission_classes = (permissions.AllowAny, )
	queryset = Experience.objects.all()
	serializer_class = ExperienceSerializer
	pagination_class = None
	lookup_field = 'slug'

# class ExperienceDetailView(generic.DetailView):
	# model = Experience
	# template_name = "main/Experience-detail.html"

class CertificateView(ListAPIView):
	permission_classes = (permissions.AllowAny, )
	queryset = Certificate.objects.all()
	serializer_class = CertificateSerializer
	pagination_class = None

class ContactProfileView(APIView):
      
    def post(self, request, format=None):
        serializer = ContactProfileSerializer(data=request.data)

        if serializer.is_valid():
            serializer.save()
            return Response({'message': 'Form submitted successfully!'}, status=status.HTTP_201_CREATED)
        else:
            return Response(serializer)

repo_name = "portfolio"
@csrf_exempt
def GitUpdate(request):
    if not(repo_name in os.getcwd()):
        os.chdir(repo_name)
    repo = git.Repo('./portfolio', search_parent_directories=True)
    for remote in repo.remotes:
        remote.fetch()
    head = sorted(repo.remotes.origin.refs, key=lambda t: t.commit.committed_datetime)[-1]
    head.checkout()
    return render(request, 'main/GitUpdate.html')

main/templates/main/Experience-detail.html
{% extends 'main/base.html' %}
{% load static %}

<!-- ================================
Start SEO blocks
================================= -->
{% block title %}{% endblock %}
{% block decription %}{% endblock %}
{% block keywords %}{% endblock %}
<!-- ================================
END SEO blocks
================================= -->

<!-- ================================
Start CSS blocks
================================= -->
{% block extend_header %}{% endblock %}
<!-- ================================
END CSS blocks
================================= -->

<!-- ================================
Start script blocks
================================= -->
{% block extend_footer %}{% endblock %}
<!-- ================================
END script blocks
================================= -->

<!-- ================================
Start Content
================================= -->
{% block content %}
<section>
  <div class="innerPageBannerCol">
    <div class="container">
      <div class="row g-4 g-md-3  align-items-center">
        <div class="col-md-6">
          <div class="bannerContent">
            <h1 class="xlTitle pb-md-3">{{object.name|title}}</h1>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-auto">
          <div class="authorCol">
            <h4 class="smTitle pb-3">{{object.location|title}}</h4>
          </div>
        </div>
        <div class="col-md">
          <h4 class="smTitle pb-3">{{object.date}}</h4>
        </div>
      </div>

      <div class="col-md-6 pColMain">
        <div class="pCol">
          <h4 class="smTitle pb-3">{{object.description}}</h4>              
            {% for skills in object.skills.all %}
              {% if skills.is_active %}       
                <span class="skills__name">{{skills.name}}</span>
              {% endif %}              
            {% endfor %}           
        </div>
        <div class="sectionSpaceSm">
          <div class="container">
            {{object.body|safe}}
          </div>
        </div>
      </div>    
    </div>
  </div>
</section>
{% endblock %}
<!-- ================================
End Content
================================= -->
   

main/templates/main/GitUpdate.html
<!DOCTYPE html>
<html>
<body>

<h1>Update to last commit</h1>

</body>
</html>

main/templates/main/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}{%endblock %}</title>
    <meta name="author" content="Did Coding Limited & James Granger Design">
    <link rel="canonical" href="{{request.path}}"/>
    <link rel="home" href="{% url 'main:home' %}"/>
    <meta name="description" content="{% block description %}{% endblock %}">
    <meta name="keywords" content="{% block keywords %}{% endblock %}">

    <link rel="shortcut icon" type="image/x-icon" href="{% static 'images/icon.jpg' %}">
    <link rel="apple-touch-icon" type="image/jpg" href="{% static 'images/icon.jpg' %}">

    <!-- ================================
    Start CSS
    ================================= -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://unpkg.com/swiper@7.0.5/swiper-bundle.min.css">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    {% block extend_header%}{%endblock%}
    <!-- ================================
    End CSS
    ================================= -->

  </head>
  <body>
    {% include 'main/partials/messages.html' %}
    {% include 'main/partials/nav.html' %}

    {% block content %}
    {% endblock %}

    {% include 'main/partials/footer.html' %}

    <!-- ================================
    Start Scripts
    ================================= -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="https://unpkg.com/swiper@7.0.5/swiper-bundle.min.js"></script>
    <script src="{% static 'js/script.js' %}"></script>
    {% block extend_footer %}{%endblock%}
    <!-- ================================
    End Scripts
    ================================= -->
  </body>
</html>

main/templates/main/contact.html
{% extends 'main/base.html' %}
{% load static %}

<!-- ================================
Start SEO blocks
================================= -->
{% block title %}{% endblock %}
{% block decription %}{% endblock %}
{% block keywords %}{% endblock %}
<!-- ================================
END SEO blocks
================================= -->

<!-- ================================
Start CSS blocks
================================= -->
{% block extend_header %}{% endblock %}
<!-- ================================
END CSS blocks
================================= -->

<!-- ================================
Start script blocks
================================= -->
{% block extend_footer %}{% endblock %}
<!-- ================================
END script blocks
================================= -->

<!-- ================================
Start Content
================================= -->
{% block content %}
<section>
  <div class="innerPageBannerCol">
    <div class="container">
      <div class="row g-4 g-md-3  align-items-center">
        <div class="col-md-6">
          <div class="bannerContent">
            <h1 class="xlTitle pb-md-3">Say Hi!</h1>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section>
  <div class="lightBg">
    <div class="container">
        <form id="contactForm" method="POST" action="/contact/">
        {% csrf_token %}
            <label for="name">Name</label>
            {{form.name}}

            <label for="email">Email</label>
            {{form.email}}

            <label for="subject">Message</label>
            {{form.message}}

            <input class='btn btnPrimary' type="submit" value="Submit">
        </form>
    </div>
  </div>
</section>
<!-- ================================
End Content
================================= -->
{%endblock%}
    

main/templates/main/index.html
{% extends 'main/base.html' %}
{% load static %}

<!-- ================================
Start SEO blocks
================================= -->
{% block title %}{% endblock %}
{% block decription %}{% endblock %}
{% block keywords %}{% endblock %}
<!-- ================================
END SEO blocks
================================= -->

<!-- ================================
Start CSS blocks
================================= -->
{% block extend_header %}{% endblock %}
<!-- ================================
END CSS blocks
================================= -->

<!-- ================================
Start script blocks
================================= -->
{% block extend_footer %}{% endblock %}
<!-- ================================
END script blocks
================================= -->

<!-- ================================
Start Content
================================= -->
{% block content %}
<section>
  <div class="bannerSection">
    <div class="container">
      <div class="row g-4 g-md-3  justify-content-center">
        <div class="col-md">
          <div class="bannerContent">
            <h1 class="xlTitle pb-3">Hi, I’m {{me.first_name|title}}</br></h1>
            <p>{{me.userprofile.bio}}</p>
            <div class="bannerBtnCol">
              <div class="row">
                <div class="col-auto">
                  <a download href="{{me.userprofile.cv.url}}" class="btn btnPrimary">Download Resume</a>
                </div>
                <div class="col-auto">
                  <a href="{% url 'main:contact' %}" class="btn btnOutline">Contact</a>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-auto order-md-last">
          <div class="bannerUserImg">
            <img src="{{me.userprofile.avatar.url}}">
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% if me.userprofile.categories %}
<section>
  <div class="sectionSpaceSm darkBg">
    <div class="container">
      <div class="row pb-3">
        <div class="col">
          <h4 class="smText regular">Skills</h4>
        </div>
      </div>
      <div class="sliderOuter">
        <div class="swiper skillsSwiper">
          <div class="swiper-wrapper">
            {% for category in me.userprofile.categories.all %}
              {% if category.is_active %}
              <div class="swiper-slide">
                <div class="cardStyle1">
                  <h4 class="mdTitle cs1Title">{{category.name}}</h4>
                  {% for skills in category.skill_set.all %}
                    {% if skills.is_active %}  
                      <span class="skills__name">{{skills.name}}</span>
                    {% endif %}              
                  {% endfor %}
                </div>
              </div>
              {% endif %}
            {% endfor %}              
          </div>
        </div>            
        <div class="skill-swiper-button-next swiper-button-next swiperBtnStyle"></div>
        <div class="skill-swiper-button-prev swiper-button-prev swiperBtnStyle"></div>
        <div class="swiper-pagination swiperPaginationStyle posInitial"></div>
      </div>
    </div>
  </div>
</section>
{% endif %}

{% if Experiences %}
  <section>
    <div class="sectionSpaceSm lightBg">
      <div class="container">
        <div class="row pb-3">
          <div class="col">
            <h4 class="smText regular">Experience</h4>
          </div>
          <div class="col-auto">
            <a href="{% url 'main:Experiences' %}" class="simpleLink"><u>View all</u></a>
          </div>
        </div>
        <div class="sliderOuter">
          <div class="swiper experienceSwiper">
            <div class="swiper-wrapper">
              {% for exp in Experiences %}
                {% if exp.is_active %}
                <div class="swiper-slide">
                  <div class="cardStyle1">
                    <h4 class="mdTitle cs1Title">{{exp.name}}</a></h4>
                    <ul class="cardOptionCol">
                      <li>{{exp.date}}</li>
                      <li>{{exp.location}}</li>
                    </ul>
                    <div class="col-auto">
                      {% for skills in exp.skills.all %}  
                        {% if skills.is_active %}  
                          <span class="skills__name">{{skills.name}}</span>
                        {% endif %}              
                      {% endfor %}
                    </div>
                    <p>{{exp.description}}</p>
                      {% if exp.url %}
                        <p>{{exp.url|safe}}</p>
                      {% endif %}                      
                    <a href="{% url 'main:Experience' slug=exp.slug %}" class="simpleLink"><u>More details</u></a>
                  </div>
                </div>
                {% endif %}
              {% endfor %}              
            </div>
          </div>            
          <div class="exp-swiper-button-next swiper-button-next swiperBtnStyle"></div>
          <div class="exp-swiper-button-prev swiper-button-prev swiperBtnStyle"></div>
          <div class="swiper-pagination swiperPaginationStyle posInitial"></div>
        </div>
      </div>
    </div>
  </section>
{% endif %}

{% if certificates %}
  <section>
    <div class="sectionSpaceSm darkBg">
      <div class="container">
        <div class="row pb-3">
          <div class="col">
            <h4 class="smText regular">Education</h4>
          </div>
        </div>
        <div class="sliderOuter">
          <div class="swiper certificatesSlider">
            <div class="swiper-wrapper">
              {% for c in certificates %}
                {% if c.is_active %}
                <div class="swiper-slide">
                  <div class="cardStyle1">
                    <h4 class="mdTitle cs1Title">{{c.title}}</a></h4>
                    <ul class="cardOptionCol">
                      <li>{{c.date}}</li>
                      <li>{{c.organisation}}</li>
                    </ul>
                    <div class="col-auto">
                      {% for skills in c.skills.all %}  
                        {% if skills.is_active %}  
                          <span class="skills__name">{{skills.name}}</span>
                        {% endif %}              
                      {% endfor %}
                    </div>                      
                      <p>{{c.description|safe}}</p>
                      {% if c.url %}
                        <p>{{c.url|safe}}</p>
                      {% endif %}
                  </div>
                </div>
                {% endif %}
              {% endfor %}              
            </div>
          </div>            
          <div class="cert-swiper-button-next swiper-button-next swiperBtnStyle"></div>
          <div class="cert-swiper-button-prev swiper-button-prev swiperBtnStyle"></div>
          <div class="swiper-pagination swiperPaginationStyle posInitial"></div>
        </div>
      </div>
    </div>
  </section>
{% endif %}

{% if portfolio %}
  <section>
    <div class="sectionSpace lightBg">
      <div class="container">
        <div class="portfolioCol">
          <div class="row pb-3">
            <div class="col">
              <h4 class="smText regular">Recent Project</h4>
            </div>
            <div class="col-auto">
              <a href="{% url 'main:portfolios' %}" class="simpleLink">View all</a>
            </div>
          </div>
          {% for p in portfolio %}
            {% if p.is_active %}
              <div class="portfolioCard">
                <div class="row g-4 align-items-center">
                  <div class="col-md-auto">
                    <div class="portfolioImgCol">
                      <a href="{% url 'main:portfolio' slug=p.slug %}"><img src="{{p.image.url}}" alt="..."></a>
                    </div>
                  </div>
                  <div class="col-md">
                    <div class="portfolioContentCol">
                      <h4 class="lgTitle"><a href="{% url 'main:portfolio' slug=p.slug %}">{{p.name}}</a></h4>
                      <ul class="portfolioOption">
                        <li><span class="dateLbl">{{p.date.year}}</span></li>
                      </ul>
                      <p>{{p.description}}</p>
                    </div>
                  </div>
                </div>
              </div>
            {% endif %}
          {% endfor %}
        </div>
      </div>
    </div>
  </section>
{% endif %}

{% if testimonials %}  
  <section>
    <div class="testimonialCol">
      <h4 class="smText regular d-block">Testimonials</h4>
      <div class="testimonialSlider">
        <div class="swiper testimonialSwiper">
          <div class="swiper-wrapper">
            {% for t in testimonials %}
              {% if t.is_active %}
              <div class="swiper-slide">
                <div class="testimonialCard">
                  <div class="row align-items-center">
                    <div class="col-sm-auto">
                      <div class="tImgCol">
                        <img src="{{t.thumbnail.url}}" alt="...">
                      </div>
                    </div>
                    <div class="col-sm">
                      <div class="tContentCol">
                        <h4 class="xsTitle bold">{{t.name}} - {{t.role}}</h4>
                        <p>{{t.quote}}</p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              {% endif %}
            {% endfor %}
          </div>
          <div class="test-swiper-button-next swiper-button-next swiperBtnStyle"></div>
          <div class="test-swiper-button-prev swiper-button-prev swiperBtnStyle"></div>
        </div>
      </div>
    </div>
  </section>
{% endif %}

{% endblock %}
<!-- ================================
End Content
================================= -->

main/templates/main/portfolio.html
{% extends 'main/base.html' %}
{% load static %}

<!-- ================================
Start SEO blocks
================================= -->
{% block title %}{% endblock %}
{% block decription %}{% endblock %}
{% block keywords %}{% endblock %}
<!-- ================================
END SEO blocks
================================= -->

<!-- ================================
Start CSS blocks
================================= -->
{% block extend_header %}{% endblock %}
<!-- ================================
END CSS blocks
================================= -->

<!-- ================================
Start script blocks
================================= -->
{% block extend_footer %}{% endblock %}
<!-- ================================
END script blocks
================================= -->

<!-- ================================
Start Content
================================= -->
{% block content %}
<section>
  <div class="innerPageBannerCol">
    <div class="container">
      <div class="row g-4 g-md-3  align-items-center">
        <div class="col-md-6">
          <div class="bannerContent">
            <h1 class="xlTitle pb-md-3">See my recent personnal projects below</h1>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section>
  <div class="lightBg">
    <div class="container">
      <div class="portfolioContentMain">
        <div class="row g-3 g-md-4 g-lg-5 portfolioRow">
          {% for obj in object_list %}
          <div class="col-md-6 pColMain">
            <div class="pCol">
              <a href="{% url 'main:portfolio' slug=obj.slug %}" >
              <img src="{{obj.image.url}}" alt="..." class="pImg">
              </a>
            </div>
          </div>
          {% endfor %}
          
        </div>
      </div>
    </div>
  </div>
</section>
<!-- ================================
End Content
================================= -->
{% endblock%}    